# Generated by Django 2.0.2 on 2019-02-21 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_auto_20190215_1208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basevendeur',
            name='product',
        ),
        migrations.AlterField(
            model_name='basevendeur',
            name='produit',
            field=models.TextField(blank=True, verbose_name='Ses produits sur skerli et leur prix'),
        ),
    ]
